name: onec server build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Актуализация
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Извлечение версии 1С из файла
        shell: bash
        run: echo "::set-output name=version::$(cat ONEC_VERSION | tail -n1)"
        id: extract_version

      - name: Извлечение версии 1С для определения варинта сборки
        env: 
          ONEC_VERSION: ${{ steps.extract_version.outputs.version }}   
        shell: bash
        run: echo "::set-output name=version::$(echo ONEC_VERSION | cut -d'.' -f3)"
        id: build_version

      
      ######################
      # Login to DockerHub #
      ######################
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ####################
      # Login to GHCR.io #
      ####################
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages new version
        uses: docker/build-push-action@v2
        env: 
          ONEC_VERSION: ${{ steps.extract_version.outputs.version }}        
        with:
          context: .
          file: Dockerfile
          build-args: |
            ONEC_USERNAME=${{ secrets.ONEC_USERNAME }}
            ONEC_PASSWORD=${{ secrets.ONEC_PASSWORD }}
            ONEC_VERSION=${{ steps.extract_version.outputs.version }}
          push: true
          tags: |
            ghcr.io/thedemoncat/onec-server-ws:${{ steps.extract_version.outputs.version }}